### ISSUE TITLE
403 error when attempting to run

### ISSUE THREAD

**Issue by trypsynth** [cartertemm/agdb#1]
Hi,
Today I tried to scrape the database, as I don't have a local copy anymore. However, after installing everything in my venv and running:
```bash
python3 agdb.py games.json
```
I get:
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://audiogames.net/
```
Did this tool break? Am I missing something?
Thanks.

**Comment by cartertemm** [comment]
This is the fault of the Cloudflare configuration, likely changed following the downtime a month ago. We will have to set required cookies/headers, or better yet let a module like [cloudscraper](https://pypi.org/project/cloudscraper/) handle it for us.

I'll patch this soon. Thanks for the find!
